version: 2.1
jobs:
  bundle-install:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - attach_workspace:
        at: ~/repo
      - restore_cache:
        keys:
          - bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
  two:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run: echo 'Hail2U!'

workflows:
  version: 2.1
  test_workflow:
    jobs:
      - bundle-install
      - two