version: 2.1
jobs:
  bundle-install:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  generate-test-env-file:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: |
          touch .env.test
          echo 'DB_HOST=0.0.0.0' > .env.test
          echo 'DB_PORT=5432' > .env.test
          echo 'DB_USER=postgres' > .env.test
          echo 'DB_TIMEOUT=30' > .env.test

  run-tests:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: bundle install
      - run: bundle exec rspec spec

workflows:
  version: 2.1
  build-test-push:
    jobs:
      - bundle-install
      - run-tests:
          requires:
            - bundle-install